# Generated by gen-builder
# Configuration: PyTorch 2.9 + CUDA 12.6
# Note: This image is CUDA 12.6 compatible and will run on CUDA 12.6+ hosts
FROM cozycreator/gen-worker:cuda12.6-torch2.9

WORKDIR /app

# Copy application code
COPY . .

# Install dependencies (PyTorch already in base image)
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir .

# Generate manifest (bakes model key->id mapping into the image)
RUN mkdir -p /app/.cozy && \
    python -m gen_worker.discover > /app/.cozy/manifest.json

# Set environment variables
ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=compute,utility
ENV COZY_DEPLOYMENT_ID="sdxl-turbo-test"
ENV HF_HOME="/app/.cache/huggingface"

# Start the gen-worker runtime (connects to orchestrator via gRPC)
CMD ["python", "-m", "gen_worker.entrypoint"]
